name: First CI Job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello GitHub Actions"
      - name: Create file
        run: echo "Workspace file created" > test.txt
      - name: Show file
        run: cat test.txt
